### ISSUE TITLE
paired end mode not working?

### ISSUE THREAD

**Issue by aldertzomer** [bcgsc/biobloom#36] opened 2018-11-05 12:26 UTC
Hi,
I'm trying to use your software as described in the example with paired end fq reads:

biobloomcategorizer  --fq -e -p test123 -f "mg1655.bf"  18072D-01-03_S71_L006_R1_001_val_1.fq.gz 18072D-01-03_S71_L006_R2_001_val_2.fq.gz -t 16

However then the program just tells me I'm doing something wrong. Without -e option it works, however then I get the matching/non-matching reads in one file, non-interleaved, which is not what I want. I assume paired end information is not used. Is there a bug somewhere that keeps biobloomcategorizer from recognizing 2 files as paired end reads when using the -e option?

**Comment by aldertzomer** [comment] 2018-11-08 10:33
Error message with option -e:

Input: 
biobloomcategorizer --fq -e -p test -f /mnt/data/klif/svermeulen/Scripts_test/BioBloomTools/database/test_db.bf S70_R1.fastq.gz S70_R2.fastq.gz

Output: 
Usage of paired end mode:
BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [FILEPAIR1] [FILEPAIR2]
or BioBloomCategorizer [OPTION]... -f "[FILTER1]..." [SMARTPAIR]

No error message with option -e and 1 file 

biobloomcategorizer --fq -e -p test -f /mnt/data/klif/svermeulen/Scripts_test/BioBloomTools/database/test_db.bf S70_R1.fastq.gz

Output:
Starting to Load Filters.
Loaded Filter: test_db
Filter Loading Complete.
Filtering Start
File written to: test_test_db_1.
File written to: test_test_db_2.
File written to: test_noMatch_1.
File written to: test_noMatch_2.
File written to: test_multiMatch_1.
File written to: test_multiMatch_2.
Total Reads:121994
Writing file: test_summary.tsv

--version output:
biobloomcategorizer (BIOBLOOMTOOLS) 2.1.2-2-g0703

**Comment by aldertzomer** [comment] 2018-11-08 10:37
To add, it works with interleaved files (although the reverse read of the pair gets placed in the forward (_1) file and the forward read gets placed in the reverse (_2) file

**Comment by JustinChu** [comment] 2018-11-08 23:12
Thanks for the report. I've found the bug and it will be fixed soon.
The smart pairing option is assigning the (_1) and (_2) arititrarally based on which it sees first. I agree that the order should be changed though and I will change that as well.

**Comment by JustinChu** [comment] 2018-11-08 23:41
The bug should be fixed in the lastest version of the master branch 8a47ccb1e55d4adf7086abeed245a08feefebe17.

Sorry for the problem, turns out the new smart pairing code was the cause of the issue. When only one file is listed there should indeed be no error.

Thanks again.

**Comment by aldertzomer** [comment] 2018-11-09 13:56
It works pefectly! Thank you very much. We can now screen our metagenomics for contaminating ( in our case non-human) host DNA in minutes.

**Comment by JustinChu** [comment] 2018-11-09 23:13
Great I'll make sure the fix is present in the release version of 2.1.2.

**Closed by JustinChu** 2018-11-09 23:13 UTC
Labels: bug
